//sometimes we faced the problem occured by the pollution of global scope, to remove the pollution generated by the global scope variables we use IIFE functions

(function pk(){  //named IIFE => cause it has name
    console.log("pawan");
})();


( (city) => {   //simple IIFE
    console.log(`pawan ${city}`);
})('dehradun');



// =================function callstack================

function one(){
    console.log("one")
    two()
}
function two(){
    console.log("two")
    three()
}
function three(){
    console.log("three")
}
one()
two()
three()




